/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package U1_P6;

import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;


/**
 *
 * @author Marcial
 */
public class Practica extends javax.swing.JFrame {
    
    private Controlador controlador = new Controlador();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Practica.class.getName());

    /**
     * Creates new form Practica
     */
    public Practica() {
        initComponents();
        txtEdad.setEditable(false);
        txtHoraIngreso.setEditable(false);
        txtHoraEgreso2.setEditable(false);
        this.setLayout(new java.awt.BorderLayout());
        this.setLocationRelativeTo(null);
        setResizable(true);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        txtApellidoMaterno = new javax.swing.JTextField();
        cboGenero = new javax.swing.JComboBox<>();
        jdNacimiento = new com.toedter.calendar.JDateChooser();
        txtEdad = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtHoraIngreso = new javax.swing.JTextField();
        btnGuardarIngreso = new javax.swing.JButton();
        jdIngreso = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlergias = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDiagnostico = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        btnGuardarRegistro = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtBuscarRegistro = new javax.swing.JTextField();
        btnBuscarRegistro = new javax.swing.JButton();
        rbAlta = new javax.swing.JRadioButton();
        rbHospitalizacion = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        txtHoraEgreso = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacionEgreso = new javax.swing.JTextArea();
        btnDarAlta = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtBuscarEgreso = new javax.swing.JTextField();
        btnBuscarEgreso = new javax.swing.JButton();
        txtHoraEgreso2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblPacientes = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        txtBuscarVista = new javax.swing.JTextField();
        btnBuscarVista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido Paterno:");

        jLabel3.setText("Apellido Materno:");

        jLabel4.setText("Genero:");

        jLabel5.setText("Fecha de nacimiento:");

        jLabel6.setText("Edad:");

        jLabel7.setText("Peso:");

        jLabel8.setText("Fecha de Ingreso:");

        jLabel9.setText("Hora de Ingreso:");

        txtNombre.addActionListener(this::txtNombreActionPerformed);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtApellidoPaterno.addActionListener(this::txtApellidoPaternoActionPerformed);
        txtApellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoPaternoKeyTyped(evt);
            }
        });

        txtApellidoMaterno.addActionListener(this::txtApellidoMaternoActionPerformed);
        txtApellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoMaternoKeyTyped(evt);
            }
        });

        cboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Femenino", "Masculino", " " }));

        jdNacimiento.addPropertyChangeListener(this::jdNacimientoPropertyChange);

        txtEdad.addActionListener(this::txtEdadActionPerformed);

        btnGuardarIngreso.setText("Guardar");
        btnGuardarIngreso.addActionListener(this::btnGuardarIngresoActionPerformed);

        jdIngreso.addPropertyChangeListener(this::jdIngresoPropertyChange);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnGuardarIngreso)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre)
                                    .addComponent(txtApellidoPaterno)
                                    .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEdad)
                            .addComponent(txtPeso)
                            .addComponent(txtHoraIngreso)
                            .addComponent(jdIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jdNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jdIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtHoraIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnGuardarIngreso)
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Ingreso", jPanel1);

        jLabel12.setText("Alergias:");

        jLabel13.setText("Observaciones:");

        jLabel14.setText("Diagnostico");

        txtAlergias.setColumns(20);
        txtAlergias.setRows(5);
        jScrollPane2.setViewportView(txtAlergias);

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane3.setViewportView(txtObservaciones);

        txtDiagnostico.setColumns(20);
        txtDiagnostico.setRows(5);
        jScrollPane4.setViewportView(txtDiagnostico);

        jLabel15.setText("Salida:");

        btnGuardarRegistro.setText("Guardar");
        btnGuardarRegistro.addActionListener(this::btnGuardarRegistroActionPerformed);

        jLabel10.setText("Buscar");

        txtBuscarRegistro.addActionListener(this::txtBuscarRegistroActionPerformed);

        btnBuscarRegistro.setText("Buscar");
        btnBuscarRegistro.addActionListener(this::btnBuscarRegistroActionPerformed);

        buttonGroup1.add(rbAlta);
        rbAlta.setText("Alta");
        rbAlta.addActionListener(this::rbAltaActionPerformed);

        buttonGroup1.add(rbHospitalizacion);
        rbHospitalizacion.setText("Hospitalización");
        rbHospitalizacion.addActionListener(this::rbHospitalizacionActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(txtBuscarRegistro))
                        .addGap(29, 29, 29)
                        .addComponent(btnBuscarRegistro))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13)
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbAlta)
                            .addComponent(rbHospitalizacion))))
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarRegistro)
                .addGap(209, 209, 209))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtBuscarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarRegistro))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel12)))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(75, 75, 75))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(rbAlta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbHospitalizacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(btnGuardarRegistro)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Registro", jPanel2);

        txtHoraEgreso.setText("Hora de Egreso:");

        jLabel11.setText("Observaciones:");

        txtObservacionEgreso.setColumns(20);
        txtObservacionEgreso.setRows(5);
        jScrollPane1.setViewportView(txtObservacionEgreso);

        btnDarAlta.setText("Dar de alta");
        btnDarAlta.addActionListener(this::btnDarAltaActionPerformed);

        jLabel16.setText("Buscar:");

        btnBuscarEgreso.setText("Buscar");
        btnBuscarEgreso.addActionListener(this::btnBuscarEgresoActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHoraEgreso)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBuscarEgreso)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtHoraEgreso2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(42, 42, 42)
                        .addComponent(btnBuscarEgreso))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btnDarAlta)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtBuscarEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarEgreso))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoraEgreso)
                    .addComponent(txtHoraEgreso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(btnDarAlta)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Egreso", jPanel3);

        tblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tblPacientes);

        jScrollPane5.setViewportView(jScrollPane7);

        jLabel17.setText("Buscar:");

        btnBuscarVista.setText("Buscar");
        btnBuscarVista.addActionListener(this::btnBuscarVistaActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarVista, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarVista)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtBuscarVista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarVista))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("Vista", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarEgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEgresoActionPerformed
        Paciente paciente = controlador.buscarEgreso(txtBuscarEgreso.getText());
        if (paciente == null) {
            JOptionPane.showMessageDialog(this,"El paciente no puede egresar.");
            return;
        }
        txtHoraEgreso2.setText(controlador.horaActual());
        txtObservacionEgreso.setText("");
    }//GEN-LAST:event_btnBuscarEgresoActionPerformed

    private void txtBuscarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarRegistroActionPerformed

    private void rbAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAltaActionPerformed

    private void rbHospitalizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHospitalizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbHospitalizacionActionPerformed

    private void btnBuscarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRegistroActionPerformed
        Paciente paciente = controlador.buscarRegistro(txtBuscarRegistro.getText());

        if (paciente == null) {
            JOptionPane.showMessageDialog(this,"Paciente no encontrado");
            return;
        }
        txtAlergias.setText(paciente.getAlergias());
        txtObservaciones.setText(paciente.getObservaciones());
        txtDiagnostico.setText(paciente.getDiagnostico());
        if (paciente.getSalida() != null) {
            if (paciente.getSalida().equalsIgnoreCase("Alta")) {
                rbAlta.setSelected(true);
            } else {
            rbHospitalizacion.setSelected(true);
            }
        }
    }//GEN-LAST:event_btnBuscarRegistroActionPerformed

    private void btnGuardarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarRegistroActionPerformed
        String salida = "";
        if (rbAlta.isSelected()) {
            salida = "Alta";
        }
        if (rbHospitalizacion.isSelected()) {
            salida = "Hospitalización";
        }
        if (salida.equals("")) {
            JOptionPane.showMessageDialog(this,"Seleccione la salida");
            return;
        }
        boolean guardar = controlador.guardarRegistro(
                txtBuscarRegistro.getText(),
                txtAlergias.getText(),
                txtObservaciones.getText(),
                txtDiagnostico.getText(),
                salida);

        if (guardar) {
            JOptionPane.showMessageDialog(this,"Registro guardado");
            txtBuscarRegistro.setText("");
            txtAlergias.setText("");
            txtObservaciones.setText("");
            txtDiagnostico.setText("");
            buttonGroup1.clearSelection();
            tblPacientes.setModel(controlador.mostrarPacientes());
        } else {
            JOptionPane.showMessageDialog(this,"Paciente no encontrado");
        }
    }//GEN-LAST:event_btnGuardarRegistroActionPerformed

    private void btnDarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarAltaActionPerformed
        if(txtObservacionEgreso.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Ingrese una observación");
            return;
        }
        boolean alta = controlador.guardarEgreso(
                txtBuscarEgreso.getText(),
                txtObservacionEgreso.getText()
        );

        if(alta){
            JOptionPane.showMessageDialog(this,"Paciente dado de alta correctamente.");
            txtBuscarEgreso.setText("");
            txtHoraEgreso2.setText("");
            txtObservacionEgreso.setText("");
            tblPacientes.setModel(controlador.mostrarPacientes());
        }else{
            JOptionPane.showMessageDialog(this,"No se pudo dar de alta al paciente.");
        }
    }//GEN-LAST:event_btnDarAltaActionPerformed

    private void btnBuscarVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVistaActionPerformed
        tblPacientes.setModel(
            controlador.buscarTabla(txtBuscarVista.getText())
        );
    }//GEN-LAST:event_btnBuscarVistaActionPerformed

    private void jdIngresoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdIngresoPropertyChange
        if(jdIngreso.getDate()!=null){
            txtHoraIngreso.setText(controlador.horaActual());
        }
    }//GEN-LAST:event_jdIngresoPropertyChange

    private void btnGuardarIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarIngresoActionPerformed
        if(txtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Ingrese el nombre");
            return;
        }
        if(txtApellidoPaterno.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Ingrese el apellido paterno");
            return;
        }
        if(txtApellidoMaterno.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Ingrese el apellido materno");
            return;
        }
        if(cboGenero.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this,"Seleccione el género");
            return;
        }
        if(jdNacimiento.getDate()==null){
            JOptionPane.showMessageDialog(this,"Seleccione la fecha de nacimiento");
            return;
        }
        if(txtPeso.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Ingrese el peso");
            return;
        }
        double peso;
        try{
            peso = Double.parseDouble(txtPeso.getText());
        }catch(NumberFormatException e){

            JOptionPane.showMessageDialog(this,"Peso inválido");
            return;
        }
        if(jdIngreso.getDate()==null){
            JOptionPane.showMessageDialog(this,"Seleccione la fecha de ingreso");
            return;
        }
        int edad = controlador.calcularEdad(jdNacimiento.getDate());

        txtEdad.setText(String.valueOf(edad));
        String hora = controlador.horaActual();
        txtHoraIngreso.setText(hora);

        boolean guardado = controlador.guardarIngreso(
            txtNombre.getText(),
            txtApellidoPaterno.getText(),
            txtApellidoMaterno.getText(),
            cboGenero.getSelectedItem().toString(),
            controlador.convertirFecha(jdNacimiento.getDate()),
            edad,
            peso,
            controlador.convertirFecha(jdIngreso.getDate()),
            hora
        );
        if(guardado){
            JOptionPane.showMessageDialog(this,"Paciente guardado correctamente.");
            txtNombre.setText("");
            txtApellidoPaterno.setText("");
            txtApellidoMaterno.setText("");
            cboGenero.setSelectedIndex(0);
            jdNacimiento.setDate(null);
            txtEdad.setText("");
            txtPeso.setText("");
            jdIngreso.setDate(null);
            txtHoraIngreso.setText("");
            tblPacientes.setModel(controlador.mostrarPacientes());
        }else{
            JOptionPane.showMessageDialog(this,"Ese paciente ya existe.");
        }
    }//GEN-LAST:event_btnGuardarIngresoActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void jdNacimientoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdNacimientoPropertyChange
        if(jdNacimiento.getDate()!=null){
            txtEdad.setText(String.valueOf(
                controlador.calcularEdad(jdNacimiento.getDate())
            ));
        }
    }//GEN-LAST:event_jdNacimientoPropertyChange

    private void txtApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMaternoActionPerformed

    private void txtApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPaternoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isLetter(c) && c != KeyEvent.VK_SPACE
                && c != KeyEvent.VK_BACK_SPACE
                && c != KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPaternoKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isLetter(c) && c != KeyEvent.VK_SPACE
                && c != KeyEvent.VK_BACK_SPACE
                && c != KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoPaternoKeyTyped

    private void txtApellidoMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoMaternoKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isLetter(c) && c != KeyEvent.VK_SPACE
                && c != KeyEvent.VK_BACK_SPACE
                && c != KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoMaternoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Practica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEgreso;
    private javax.swing.JButton btnBuscarRegistro;
    private javax.swing.JButton btnBuscarVista;
    private javax.swing.JButton btnDarAlta;
    private javax.swing.JButton btnGuardarIngreso;
    private javax.swing.JButton btnGuardarRegistro;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cboGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JDateChooser jdIngreso;
    private com.toedter.calendar.JDateChooser jdNacimiento;
    private javax.swing.JRadioButton rbAlta;
    private javax.swing.JRadioButton rbHospitalizacion;
    private javax.swing.JTable tblPacientes;
    private javax.swing.JTextArea txtAlergias;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtBuscarEgreso;
    private javax.swing.JTextField txtBuscarRegistro;
    private javax.swing.JTextField txtBuscarVista;
    private javax.swing.JTextArea txtDiagnostico;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JLabel txtHoraEgreso;
    private javax.swing.JTextField txtHoraEgreso2;
    private javax.swing.JTextField txtHoraIngreso;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtObservacionEgreso;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
